In [2]:
import numpy as np
from sklearn.preprocessing import PolynomialFeatures

In [102]:
a=np.array([[2],[7]])
b=np.array([2,5])

In [59]:
p=PolynomialFeatures(degree=2,interaction_only=True)
p.fit_transform(a)

array([[1., 0., 1., 2., 0., 0., 2.]])

In [36]:
from sklearn.linear_model import LinearRegression
l=LinearRegression()

In [60]:
l.fit(p.fit_transform(a),b)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [53]:
l.coef_

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [55]:
l.intercept_

array([2., 5., 7.])

In [88]:
np.shape(a)

(2, 1, 3)

In [104]:
a.reshape(2,1)

array([[2],
       [7]])

In [109]:
l1=LinearRegression()
l1.fit(a.reshape(2,1),b.reshape(2,1))
l1.coef_

array([[0.6]])